version: "3.9"
services:
  web:
    build: .
    container_name: alarm_dash_app
    restart: unless-stopped
    networks: [frontend]

  nginx:
    image: nginx:1.27-alpine
    container_name: alarm_dash_nginx
    restart: unless-stopped
    depends_on: [web]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"  # เปลี่ยนเป็น 8080:80 ก็ได้ถ้า port 80 ถูกใช้แล้ว
    networks: [frontend]

networks:
  frontend:
    driver: bridge
